@startuml
title
    <img:assets/logos/calypso.svg{scale=0.2}>

    Terminal Storage Card API - 2.0.+ (2026-06-15)
end title

' == THEME (class) ==

'Couleurs issues de : https://htmlcolorcodes.com/fr/tableau-de-couleur/tableau-de-couleur-design-plat/
!define C_GREY1 F8F9F9
!define C_GREY2 F2F3F4
!define C_GREY3 E5E7E9
!define C_GREY4 D7DBDD
!define C_GREY5 CACFD2
!define C_GREY6 BDC3C7
!define C_LINK 3498DB
!define C_USE 27AE60

skinparam ClassBorderThickness 2
skinparam ArrowThickness 2

' Yellow
skinparam ClassBackgroundColor #FEFECE
skinparam ClassBorderColor #D4AC0D
' Red
skinparam ClassBackgroundColor<<red>> #FDEDEC
skinparam ClassBorderColor<<red>> #E74C3C
hide <<red>> stereotype
' Purple
skinparam ClassBackgroundColor<<purple>> #F4ECF7
skinparam ClassBorderColor<<purple>> #8E44AD
hide <<purple>> stereotype
' blue
skinparam ClassBackgroundColor<<blue>> #EBF5FB
skinparam ClassBorderColor<<blue>> #3498DB
hide <<blue>> stereotype
' Green
skinparam ClassBackgroundColor<<green>> #E9F7EF
skinparam ClassBorderColor<<green>> #27AE60
hide <<green>> stereotype
' Grey
skinparam ClassBackgroundColor<<grey>> #EAECEE
skinparam ClassBorderColor<<grey>> #2C3E50
hide <<grey>> stereotype

' == CONTENT ==

legend top
    * __External public API references__
    *** <back:yellow>**Calypsonet Terminal Reader API**</back>
    * __Text__
    *** <color:blue><b>New element added since the last version
    *** <color:red><s><b>Element marked as deprecated since the last version
    *** <s><b>Element marked as deprecated
    *** <color:grey><b>Work in progress...
    * __Object__
    *** <back:#EBF5FB><color:#3498DB><b>Factory or interface provided by the factory
    *** <back:#FEFECE><color:#D4AC0D><b>Interface that cannot be instantiated directly by the factory
    *** <back:#FDEDEC><color:#E74C3C><b>SPI (Service Provider Interface) to be provided by the end-user
    *** <back:#E9F7EF><color:#27AE60><b>Class, enum or error
end legend

package "terminal.storagecard" as root {
    +class "**final** StorageCardApiProperties" as ApiProperties <<green>> {
        +{static} **final** VERSION: String
    }
    +interface "StorageCardApiFactory" as StorageCardApiFactory <<blue>> {
        +createStorageCardSelectionExtension(productType: ProductType) → StorageCardSelectionExtension

        +createStorageCardTransactionManager(reader: <back:yellow>CardReader</back>, card: StorageCard) → StorageCardTransactionManager
    }

    package "card" as card {
        +interface "<<<back:yellow>CardSelectionExtension</back>>>\nStorageCardSelectionExtension" as StorageCardSelectionExtension <<blue>> {
            +prepareReadBlock(blockAddress: Int) → StorageCardSelectionExtension
            +prepareReadBlocks(fromBlockAddress: Int, toBlockAddress: Int) → StorageCardSelectionExtension
            .. **ST25 / SRT512** ..
            +prepareSt25ReadSystemBlock() → StorageCardSelectionExtension
            .. **Mifare Classic** ..
            +prepareMifareClassicAuthenticate(blockAddress: Int, mifareClassicKeyType: MifareClassicKeyType, key: ByteArray) → StorageCardSelectionExtension
            +prepareMifareClassicAuthenticate(blockAddress: Int, mifareClassicKeyType: MifareClassicKeyType, keyNumber: Int) → StorageCardSelectionExtension
        }
        +interface "<<<back:yellow>SmartCard</back>>>\nStorageCard" as StorageCard {
            +getProductType() → ProductType
            +getUID() → ByteArray
            +getBlock(blockAddress: Int) → ByteArray
            +getBlocks(fromBlockAddress: Int, toBlockAddress: Int) → ByteArray
            .. **ST25 / SRT512** ..
            +getSystemBlock() → ByteArray?
        }
        +enum "ProductType" as ProductType <<green>> {
            MIFARE_ULTRALIGHT
            MIFARE_CLASSIC_1K
            MIFARE_CLASSIC_4K
            ST25_SRT512

            +getBlockCount() → Int
            +getBlockSize() → Int
            +hasSystemBlock() → Boolean
            +hasWriteAcknowledgment() → Boolean
            +hasAuthentication() → Boolean
        }
    }

    +enum "MifareClassicKeyType" as MifareClassicKeyType <<green>> {
        KEY_A
        KEY_B
    }

    package "transaction" as transaction {
        +interface "<<<back:yellow>CardTransactionManager</back>>>\nStorageCardTransactionManager" as StorageCardTransactionManager <<blue>> {
            ' Standard Read/Write
            +prepareReadBlock(blockAddress: Int) → StorageCardTransactionManager
            +prepareReadBlocks(fromBlockAddress: Int, toBlockAddress: Int) → StorageCardTransactionManager
            +prepareWriteBlocks(fromBlockAddress: Int, data: ByteArray) → StorageCardTransactionManager
            +<color:blue>prepareWriteBlocks(fromBlockAddress: Int, data: ByteArray, idCommand: Int) → StorageCardTransactionManager
            .. **ST25 / SRT512** ..
            +prepareSt25ReadSystemBlock() → StorageCardTransactionManager
            +prepareSt25WriteSystemBlock(data: ByteArray) → StorageCardTransactionManager
            +<color:blue>prepareSt25WriteSystemBlock(data: ByteArray, idCommand: Int) → StorageCardTransactionManager
            .. **Mifare Classic** ..
            +prepareMifareClassicAuthenticate(blockAddress: Int, mifareClassicKeyType: MifareClassicKeyType, key: ByteArray) → StorageCardTransactionManager
            +prepareMifareClassicAuthenticate(blockAddress: Int, mifareClassicKeyType: MifareClassicKeyType, keyNumber: Int) → StorageCardTransactionManager
        }
    }

    +interface "StorageCardError" as StorageCardError <<green>> {
        +getBlockAddress() → Int?
        +<color:blue>getIdCommand() → Int?
    }
    +class "<<<back:yellow>ReaderCommunication</back>>>\nSCReaderCommunication" as SCReaderCommunication <<green>> implements StorageCardError {
    }
    +class "SCAuthenticationFailed" as SCAuthenticationFailed <<green>> implements StorageCardError {
    }
    +class "<<<back:yellow>CardCommunication</back>>>\nSCCardCommunication" as SCCardCommunication <<green>> implements StorageCardError {
    }
    +class "<<<back:yellow>InvalidCardResponse</back>>>\nSCInvalidCardResponse" as SCInvalidCardResponse <<green>> implements StorageCardError {
    }
}

' Associations
StorageCardApiFactory ..> StorageCardSelectionExtension #C_LINK : create >
StorageCardApiFactory ..> StorageCardTransactionManager #C_LINK : create >
StorageCardApiFactory .right.> StorageCard #C_USE : use >
StorageCardApiFactory .right.> ProductType #C_USE : use >
StorageCard ..> ProductType #C_USE : provide >
StorageCardSelectionExtension ..> MifareClassicKeyType #C_USE : use >
StorageCardTransactionManager ..> MifareClassicKeyType #C_USE : use >

' == LAYOUT ==

StorageCardApiFactory -[hidden]- StorageCardSelectionExtension
StorageCardApiFactory -[hidden]- StorageCardTransactionManager
ProductType -[hidden]- StorageCardError
SCReaderCommunication -[hidden]down- SCAuthenticationFailed

' == STYLE ==

package root #C_GREY1 {}
package root.card #C_GREY2 {}
package root.transaction #C_GREY2 {}

@enduml