@startuml
title
    <img:../assets/logo.svg{scale=0.2}>

    Terminal Storage Card API - 1.1.0 (2025-12-05)
end title

' == THEME ==

'Couleurs issues de : https://htmlcolorcodes.com/fr/tableau-de-couleur/tableau-de-couleur-design-plat/
!define C_GREY1 F8F9F9
!define C_GREY2 F2F3F4
!define C_GREY3 E5E7E9
!define C_GREY4 D7DBDD
!define C_GREY5 CACFD2
!define C_GREY6 BDC3C7
!define C_LINK 3498DB
!define C_USE 27AE60

skinparam ClassBorderThickness 2
skinparam ArrowThickness 2

' Yellow
skinparam ClassBackgroundColor #FEFECE
skinparam ClassBorderColor #D4AC0D
' Red
skinparam ClassBackgroundColor<<red>> #FDEDEC
skinparam ClassBorderColor<<red>> #E74C3C
hide <<red>> stereotype
' Purple
skinparam ClassBackgroundColor<<purple>> #F4ECF7
skinparam ClassBorderColor<<purple>> #8E44AD
hide <<purple>> stereotype
' blue
skinparam ClassBackgroundColor<<blue>> #EBF5FB
skinparam ClassBorderColor<<blue>> #3498DB
hide <<blue>> stereotype
' Green
skinparam ClassBackgroundColor<<green>> #E9F7EF
skinparam ClassBorderColor<<green>> #27AE60
hide <<green>> stereotype
' Grey
skinparam ClassBackgroundColor<<grey>> #EAECEE
skinparam ClassBorderColor<<grey>> #2C3E50
hide <<grey>> stereotype

' == CONTENT ==

legend top
    __Colors legend__ :
    * __External API references__ :
    ** <back:yellow>**keypop-reader-java-api**</back>
end legend

package "terminal.storagecard" as root {
    +class "**final** StorageCardApiProperties" as ApiProperties <<green>> {
        +{static} **final** String VERSION
    }
    +interface "StorageCardApiFactory" as StorageCardApiFactory <<blue>> {
        +StorageCardSelectionExtension createStorageCardSelectionExtension(ProductType productType)

        +StorageCardTransactionManager createStorageCardTransactionManager(<back:yellow>CardReader reader</back>, StorageCard card)
    }

    package "card" as card {
        +interface "<<<back:yellow>CardSelectionExtension</back>>>\nStorageCardSelectionExtension" as StorageCardSelectionExtension <<blue>> {
            +StorageCardSelectionExtension prepareReadBlock(int blockAddress)
            +StorageCardSelectionExtension prepareReadBlocks(int fromBlockAddress, int toBlockAddress)
            .. **Mifare Classic** ..
            +<color:blue>StorageCardSelectionExtension prepareMifareClassicAuthenticate(int blockAddress, MifareClassicKeyType mifareClassicKeyType, byte[] key)
            +<color:blue>StorageCardSelectionExtension prepareMifareClassicAuthenticate(int blockAddress, MifareClassicKeyType mifareClassicKeyType, int keyNumber)
        }
        +interface "<<<back:yellow>SmartCard</back>>>\nStorageCard" as StorageCard {
            +ProductType getProductType()
            +byte[] getUID()
            +byte[] getBlock(int blockAddress)
            +byte[] getBlocks(int fromBlockAddress, int toBlockAddress)
            .. **ST25 / SRT512** ..
            +byte[] getSystemBlock()
        }
        +enum "ProductType" as ProductType <<green>> {
            MIFARE_ULTRALIGHT
            <color:blue>MIFARE_CLASSIC_1K
            <color:blue>MIFARE_CLASSIC_4K
            ST25_SRT512

            +getBlockCount(): int
            +getBlockSize(): int
            +hasSystemBlock(): boolean
            +hasWriteAcknowledgment(): boolean
            +<color:blue>hasAuthentication(): boolean
        }
    }

    +enum "<color:blue>MifareClassicKeyType" as MifareClassicKeyType <<green>> {
        <color:blue>KEY_A
        <color:blue>KEY_B
    }

    package "transaction" as transaction {
        +interface "<<<back:yellow>CardTransactionManager</back>>>\nStorageCardTransactionManager" as StorageCardTransactionManager <<blue>> {
            ' Standard Read/Write
            +StorageCardTransactionManager prepareReadBlock(int blockAddress)
            +StorageCardTransactionManager prepareReadBlocks(int fromBlockAddress, int toBlockAddress)
            +StorageCardTransactionManager prepareWriteBlocks(int fromBlockAddress, byte[] data)
            .. **ST25 / SRT512** ..
            +<color:red><s>StorageCardTransactionManager prepareReadSystemBlock()
            +<color:red><s>StorageCardTransactionManager prepareWriteSystemBlock(byte[] data)
            +<color:blue>StorageCardTransactionManager prepareSt25ReadSystemBlock()
            +<color:blue>StorageCardTransactionManager prepareSt25WriteSystemBlock(byte[] data)
            .. **Mifare Classic** ..
            +<color:blue>StorageCardTransactionManager prepareMifareClassicAuthenticate(int blockAddress, MifareClassicKeyType mifareClassicKeyType, byte[] key)
            +<color:blue>StorageCardTransactionManager prepareMifareClassicAuthenticate(int blockAddress, MifareClassicKeyType mifareClassicKeyType, int keyNumber)
        }
    }

    +interface "StorageCardException" as StorageCardException <<green>> {
        +Integer getBlockAddress()
    }
    +class "<<<back:yellow>ReaderCommunicationException</back>>></color>\n**final** SCReaderCommunicationException" as SCReaderCommunicationException <<green>> implements StorageCardException {
        +SCReaderCommunicationException (Integer blockAddress, String message)
        +SCReaderCommunicationException (Integer blockAddress, String message, Throwable cause)
    }
    +class "<color:blue>**final** SCAuthenticationFailedException" as SCAuthenticationFailedException <<green>> implements StorageCardException {
        +<color:blue>SCAuthenticationFailedException (Integer blockAddress, String message)
        +<color:blue>SCAuthenticationFailedException (Integer blockAddress, String message, Throwable cause)
    }
    +class "<<<back:yellow>CardCommunicationException</back>>></color>\n**final** SCCardCommunicationException" as SCCardCommunicationException <<green>> implements StorageCardException {
        +SCCardCommunicationException (Integer blockAddress, String message)
        +SCCardCommunicationException (Integer blockAddress, String message, Throwable cause)
    }
    +class "<<<back:yellow>InvalidCardResponseException</back>>></color>\n**final** SCInvalidCardResponseException" as SCInvalidCardResponseException <<green>> implements StorageCardException {
        +SCInvalidCardResponseException (Integer blockAddress, String message)
        +SCInvalidCardResponseException (Integer blockAddress, String message, Throwable cause)
    }
}

' Associations
StorageCardApiFactory ..> StorageCardSelectionExtension #C_LINK : create >
StorageCardApiFactory ..> StorageCardTransactionManager #C_LINK : create >
StorageCardApiFactory .right.> StorageCard #C_USE : use >
StorageCardApiFactory .right.> ProductType #C_USE : use >
StorageCard ..> ProductType #C_USE : provide >
StorageCardSelectionExtension ..> MifareClassicKeyType #C_USE : use >
StorageCardTransactionManager ..> MifareClassicKeyType #C_USE : use >

' == LAYOUT ==

StorageCardApiFactory -[hidden]- StorageCardSelectionExtension
StorageCardApiFactory -[hidden]- StorageCardTransactionManager
ProductType -[hidden]- StorageCardException
SCReaderCommunicationException -[hidden]down- SCAuthenticationFailedException

' == STYLE ==

package root #C_GREY1 {}
package root.card #C_GREY2 {}
package root.transaction #C_GREY2 {}

@enduml